[2024-04-21T21:04:38.970+0000] {scheduler_job_runner.py:780} ERROR - Executor reports task instance <TaskInstance: workshop2_dags.extract_db manual__2024-04-21T21:02:30.545347+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
