[2024-04-21T19:51:52.194+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:51:52.195+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T19:51:52.198+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:51:52.198+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:51:52.995+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:51:53.337+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:51:53.337+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T19:51:53.380+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:51:53.379+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T19:51:53.487+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.306 seconds
[2024-04-21T19:52:24.344+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:52:24.346+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T19:52:24.351+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:52:24.350+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:52:25.869+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:52:25.979+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:52:25.979+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T19:52:26.017+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:52:26.017+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T19:52:26.069+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.723 seconds
[2024-04-21T19:52:56.656+0000] {processor.py:161} INFO - Started process (PID=152) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:52:56.659+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T19:52:56.665+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:52:56.665+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:52:59.027+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:52:59.154+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:52:59.154+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T19:52:59.199+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:52:59.199+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T19:52:59.258+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 2.814 seconds
[2024-04-21T19:53:29.469+0000] {processor.py:161} INFO - Started process (PID=214) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:53:29.470+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T19:53:29.473+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:53:29.473+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:53:31.076+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:53:31.219+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:53:31.218+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T19:53:31.258+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:53:31.257+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T19:53:31.308+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.844 seconds
[2024-04-21T19:54:32.115+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:54:32.117+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T19:54:32.119+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:54:32.119+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:54:33.267+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:54:33.348+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:54:33.347+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T19:54:33.376+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:54:33.375+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T19:54:33.415+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.305 seconds
[2024-04-21T19:55:17.471+0000] {processor.py:161} INFO - Started process (PID=104) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:55:17.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T19:55:17.491+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:55:17.490+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:55:19.007+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:55:19.069+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:55:19.067+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T19:55:19.101+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:55:19.101+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T19:55:19.149+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.690 seconds
[2024-04-21T19:55:27.058+0000] {processor.py:161} INFO - Started process (PID=152) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:55:27.060+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T19:55:27.062+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:55:27.061+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:55:28.293+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:55:28.415+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:55:28.410+0000] {taskinstance.py:2733} ERROR - {'DAG Id': 'workshop2_dags', 'Task Id': 'extract_csv', 'Run Id': 'manual__2024-04-21T18:58:03.284812+00:00', 'Hostname': '6e4579bd97b2', 'External Executor Id': '2f67d38e-4f64-4ad9-bb79-e672cc872791'}
[2024-04-21T19:55:28.463+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:55:28.463+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=workshop2_dags, task_id=extract_csv, execution_date=20240421T185803, start_date=20240421T195448, end_date=20240421T195528
[2024-04-21T19:55:28.496+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: workshop2_dags.extract_csv manual__2024-04-21T18:58:03.284812+00:00 [up_for_retry]> in state up_for_retry
[2024-04-21T19:55:28.530+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:55:28.529+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T19:55:28.570+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:55:28.569+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T19:55:28.617+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.561 seconds
[2024-04-21T19:57:16.206+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:57:16.208+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T19:57:16.211+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:57:16.211+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:57:21.778+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:57:31.884+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:57:31.837+0000] {dagbag.py:649} ERROR - Failed to write serialized DAG: /opt/airflow/dags/Airflow/dags_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host 'mysql' (-3)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T19:57:31.886+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:57:31.885+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T19:57:32.547+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:57:32.547+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T19:57:32.627+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 16.425 seconds
[2024-04-21T19:59:03.638+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T19:59:03.640+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T19:59:03.641+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:59:03.641+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:00:41.899+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:00:41.882+0000] {timeout.py:68} ERROR - Process timed out, PID: 226
[2024-04-21T20:00:41.909+0000] {logging_mixin.py:188} WARNING - Exception ignored in: <function _collection_gced at 0x7f3d994ab430>
[2024-04-21T20:00:41.915+0000] {logging_mixin.py:188} WARNING - Traceback (most recent call last):
[2024-04-21T20:00:41.917+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/event/registry.py", line 53, in _collection_gced
[2024-04-21T20:00:41.933+0000] {logging_mixin.py:188} WARNING -     def _collection_gced(ref):
[2024-04-21T20:00:41.935+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
[2024-04-21T20:00:41.959+0000] {logging_mixin.py:188} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2024-04-21T20:00:41.962+0000] {logging_mixin.py:188} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/Airflow/dags_etl.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.8.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.8.4/best-practices.html#reducing-dag-complexity, PID: 226
[2024-04-21T20:00:43.910+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:00:54.093+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:00:53.987+0000] {dagbag.py:649} ERROR - Failed to write serialized DAG: /opt/airflow/dags/Airflow/dags_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host 'mysql' (-3)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T20:00:54.128+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:00:54.107+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:00:55.297+0000] {processor.py:161} INFO - Started process (PID=236) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:00:55.300+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:00:55.302+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:00:55.302+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:00:57.462+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:01:07.553+0000] {processor.py:715} ERROR - Error executing TaskCallbackRequest callback for file: /opt/airflow/dags/Airflow/dags_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 709, in execute_callbacks
    self._execute_task_callbacks(dagbag, request, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 762, in _execute_task_callbacks
    ti = TaskInstance.get_task_instance(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1734, in get_task_instance
    return query.one_or_none()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host 'mysql' (-3)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T20:01:26.167+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:01:20.079+0000] {dagbag.py:649} ERROR - Failed to write serialized DAG: /opt/airflow/dags/Airflow/dags_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host 'mysql' (-3)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T20:01:26.173+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:01:26.172+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:02:02.418+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:01:49.285+0000] {dagbag.py:649} ERROR - Failed to write serialized DAG: /opt/airflow/dags/Airflow/dags_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host 'mysql' (-3)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T20:02:02.506+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:02:02.484+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:02:24.673+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:02:23.603+0000] {dagbag.py:649} ERROR - Failed to write serialized DAG: /opt/airflow/dags/Airflow/dags_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host 'mysql' (-3)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T20:02:25.029+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:02:24.749+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:02:37.307+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 859, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 895, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 659, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 675, in _sync_to_db
    DAG.bulk_write_to_db(dags.values(), processor_subdir=processor_subdir, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 3059, in bulk_write_to_db
    orm_dags: list[DagModel] = session.scalars(query).unique().all()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1778, in scalars
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host 'mysql' (-3)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T20:02:54.597+0000] {processor.py:161} INFO - Started process (PID=247) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:02:54.599+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:02:54.603+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:02:54.600+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:02:56.765+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:03:06.896+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:03:06.827+0000] {dagbag.py:649} ERROR - Failed to write serialized DAG: /opt/airflow/dags/Airflow/dags_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host 'mysql' (-3)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T20:03:06.934+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:03:06.925+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:03:08.461+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:03:08.455+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:03:08.549+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 13.962 seconds
[2024-04-21T20:03:18.654+0000] {processor.py:161} INFO - Started process (PID=298) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:03:18.657+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:03:18.659+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:03:18.658+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:03:19.446+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:03:19.549+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:03:19.548+0000] {taskinstance.py:2733} ERROR - {'DAG Id': 'workshop2_dags', 'Task Id': 'extract_db', 'Run Id': 'manual__2024-04-21T18:58:03.284812+00:00', 'Hostname': '6e4579bd97b2', 'External Executor Id': '2dc226ad-e697-4576-a20a-d3480efdd335'}
[2024-04-21T20:03:19.588+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:03:19.588+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=workshop2_dags, task_id=extract_db, execution_date=20240421T185803, start_date=20240421T195448, end_date=20240421T200319
[2024-04-21T20:03:19.612+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: workshop2_dags.extract_db manual__2024-04-21T18:58:03.284812+00:00 [up_for_retry]> in state up_for_retry
[2024-04-21T20:03:19.621+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:03:19.620+0000] {taskinstance.py:2733} ERROR - {'DAG Id': 'workshop2_dags', 'Task Id': 'extract_db', 'Run Id': 'manual__2024-04-21T18:58:03.284812+00:00', 'Hostname': '6e4579bd97b2', 'External Executor Id': '2dc226ad-e697-4576-a20a-d3480efdd335'}
[2024-04-21T20:03:19.637+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:03:19.637+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=workshop2_dags, task_id=extract_db, execution_date=20240421T185803, start_date=20240421T195448, end_date=20240421T200319
[2024-04-21T20:03:19.645+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: workshop2_dags.extract_db manual__2024-04-21T18:58:03.284812+00:00 [failed]> in state failed
[2024-04-21T20:03:19.652+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:03:19.652+0000] {taskinstance.py:2733} ERROR - {'DAG Id': 'workshop2_dags', 'Task Id': 'extract_db', 'Run Id': 'manual__2024-04-21T18:58:03.284812+00:00', 'Hostname': '6e4579bd97b2', 'External Executor Id': '2dc226ad-e697-4576-a20a-d3480efdd335'}
[2024-04-21T20:03:19.670+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:03:19.670+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=workshop2_dags, task_id=extract_db, execution_date=20240421T185803, start_date=20240421T195448, end_date=20240421T200319
[2024-04-21T20:03:19.681+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: workshop2_dags.extract_db manual__2024-04-21T18:58:03.284812+00:00 [failed]> in state failed
[2024-04-21T20:03:19.715+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:03:19.714+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:03:19.749+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:03:19.748+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:03:19.807+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.159 seconds
[2024-04-21T20:04:20.180+0000] {processor.py:161} INFO - Started process (PID=337) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:04:20.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:04:20.183+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:04:20.183+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:04:21.322+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:04:21.396+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:04:21.395+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:04:21.423+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:04:21.423+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:04:21.475+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.300 seconds
[2024-04-21T20:04:24.450+0000] {processor.py:161} INFO - Started process (PID=365) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:04:24.453+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:04:24.456+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:04:24.455+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:04:25.187+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:04:25.326+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:04:25.324+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:04:25.376+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:04:25.376+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:04:25.515+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.070 seconds
[2024-04-21T20:04:55.922+0000] {processor.py:161} INFO - Started process (PID=422) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:04:55.923+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:04:55.926+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:04:55.925+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:04:56.385+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:04:56.443+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:04:56.443+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:04:56.465+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:04:56.465+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:04:56.501+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 0.582 seconds
[2024-04-21T20:05:26.718+0000] {processor.py:161} INFO - Started process (PID=478) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:05:26.720+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:05:26.722+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:05:26.721+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:05:27.312+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:05:27.386+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:05:27.386+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:05:27.410+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:05:27.410+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:05:27.462+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 0.750 seconds
[2024-04-21T20:05:57.997+0000] {processor.py:161} INFO - Started process (PID=536) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:05:57.998+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:05:58.000+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:05:58.000+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:05:59.023+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:05:59.110+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:05:59.109+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:05:59.138+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:05:59.138+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:05:59.182+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.191 seconds
[2024-04-21T20:06:42.326+0000] {processor.py:161} INFO - Started process (PID=542) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:06:42.330+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:06:42.333+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:06:42.332+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:06:44.012+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:06:44.131+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:06:44.131+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:06:44.173+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:06:44.172+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:06:44.225+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.910 seconds
[2024-04-21T20:07:14.683+0000] {processor.py:161} INFO - Started process (PID=609) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:07:14.685+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:07:14.687+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:07:14.686+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:07:15.884+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:07:16.009+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:07:16.008+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:07:16.051+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:07:16.050+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:07:16.115+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.439 seconds
[2024-04-21T20:07:46.474+0000] {processor.py:161} INFO - Started process (PID=670) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:07:46.476+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:07:46.479+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:07:46.478+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:07:47.491+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:07:47.639+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:07:47.638+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:07:47.684+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:07:47.683+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:07:47.746+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.279 seconds
[2024-04-21T20:08:20.001+0000] {processor.py:161} INFO - Started process (PID=726) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:08:20.002+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:08:20.003+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:08:20.003+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:08:20.927+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:08:20.988+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:08:20.987+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:08:21.013+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:08:21.013+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:08:21.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.052 seconds
[2024-04-21T20:08:51.600+0000] {processor.py:161} INFO - Started process (PID=783) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:08:51.603+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:08:51.605+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:08:51.605+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:09:21.973+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:09:21.651+0000] {timeout.py:68} ERROR - Process timed out, PID: 783
[2024-04-21T20:10:21.241+0000] {processor.py:161} INFO - Started process (PID=841) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:10:21.243+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:10:21.244+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:10:21.244+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:10:21.658+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:10:21.716+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:10:21.715+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:10:21.742+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:10:21.742+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:10:21.778+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 0.541 seconds
[2024-04-21T20:10:52.159+0000] {processor.py:161} INFO - Started process (PID=898) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:10:52.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:10:52.162+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:10:52.162+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:10:52.642+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:10:52.698+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:10:52.697+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:10:52.722+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:10:52.722+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:10:52.764+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 0.607 seconds
[2024-04-21T20:11:02.289+0000] {processor.py:161} INFO - Started process (PID=907) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:11:02.290+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:11:02.291+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:11:02.291+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:11:02.674+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:11:02.727+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:11:02.726+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:11:02.748+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:11:02.748+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:11:02.785+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 0.499 seconds
[2024-04-21T20:14:14.838+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:14:14.841+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:14:14.843+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:14:14.843+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:14:15.646+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:14:15.943+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:14:15.943+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:14:15.969+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:14:15.969+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:14:16.024+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.194 seconds
[2024-04-21T20:14:46.240+0000] {processor.py:161} INFO - Started process (PID=96) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:14:46.242+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:14:46.245+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:14:46.244+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:14:47.734+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:14:47.792+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:14:47.792+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:14:47.815+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:14:47.815+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:14:47.849+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.612 seconds
[2024-04-21T20:15:18.042+0000] {processor.py:161} INFO - Started process (PID=158) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:15:18.043+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:15:18.046+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:15:18.045+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:15:19.268+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:15:19.331+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:15:19.330+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:15:19.354+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:15:19.354+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:15:19.388+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.349 seconds
[2024-04-21T20:16:13.767+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:16:13.772+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:16:13.778+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:16:13.777+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:16:15.008+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:16:15.082+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:16:15.081+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:16:15.109+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:16:15.109+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:16:15.146+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.393 seconds
[2024-04-21T20:16:45.666+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:16:45.668+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:16:45.673+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:16:45.671+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:16:46.272+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:16:46.325+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:16:46.324+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:16:46.346+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:16:46.346+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:16:46.381+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 0.719 seconds
[2024-04-21T20:17:16.459+0000] {processor.py:161} INFO - Started process (PID=154) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:17:16.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:17:16.463+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:17:16.463+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:17:17.419+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:17:17.476+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:17:17.475+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:17:17.506+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:17:17.505+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:17:17.564+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.108 seconds
[2024-04-21T20:17:47.855+0000] {processor.py:161} INFO - Started process (PID=216) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:17:47.856+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:17:47.858+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:17:47.858+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:17:48.729+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:17:48.792+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:17:48.791+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:17:48.821+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:17:48.821+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:17:48.870+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.019 seconds
[2024-04-21T20:18:19.108+0000] {processor.py:161} INFO - Started process (PID=277) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:18:19.109+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:18:19.111+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:18:19.111+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:18:19.972+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:18:20.028+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:18:20.027+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:18:20.051+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:18:20.051+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:18:20.087+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 0.983 seconds
[2024-04-21T20:18:50.907+0000] {processor.py:161} INFO - Started process (PID=337) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:18:50.908+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:18:50.911+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:18:50.911+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:18:52.009+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:18:52.072+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:18:52.072+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:18:52.098+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:18:52.097+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:18:52.134+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.233 seconds
[2024-04-21T20:32:44.034+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:32:44.038+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:32:44.041+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:32:44.041+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:32:44.880+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:32:45.438+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:32:45.438+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:32:45.509+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:32:45.509+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:32:45.615+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.587 seconds
[2024-04-21T20:32:54.306+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:32:54.308+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:32:54.311+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:32:54.311+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:32:56.625+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:32:56.743+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:32:56.742+0000] {taskinstance.py:2733} ERROR - {'DAG Id': 'workshop2_dags', 'Task Id': 'transformation_db', 'Run Id': 'manual__2024-04-21T20:15:28.756069+00:00', 'Hostname': '6e4579bd97b2', 'External Executor Id': '7f2bac2b-d674-48e5-acbf-d06c55b36aff'}
[2024-04-21T20:32:56.769+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:32:56.769+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=workshop2_dags, task_id=transformation_db, execution_date=20240421T201528, start_date=20240421T201541, end_date=20240421T203256
[2024-04-21T20:32:56.796+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: workshop2_dags.transformation_db manual__2024-04-21T20:15:28.756069+00:00 [up_for_retry]> in state up_for_retry
[2024-04-21T20:32:56.806+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:32:56.805+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:32:56.834+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:32:56.834+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:32:56.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 2.570 seconds
[2024-04-21T20:33:18.778+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:33:18.782+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:33:18.794+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:33:18.794+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:33:19.790+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:33:19.866+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:33:19.865+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:33:19.894+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:33:19.894+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:33:19.930+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.170 seconds
[2024-04-21T20:33:50.766+0000] {processor.py:161} INFO - Started process (PID=93) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:33:50.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:33:50.770+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:33:50.770+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:33:51.786+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:33:51.847+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:33:51.846+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:33:51.871+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:33:51.871+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:33:51.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.143 seconds
[2024-04-21T20:34:27.566+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:34:27.567+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:34:27.571+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:34:27.570+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:34:28.663+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:34:28.739+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:34:28.738+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:34:28.767+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:34:28.766+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:34:28.813+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.251 seconds
[2024-04-21T20:34:59.078+0000] {processor.py:161} INFO - Started process (PID=93) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:34:59.079+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:34:59.081+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:34:59.080+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:35:00.246+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:35:00.324+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:35:00.323+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:35:00.372+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:35:00.371+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:35:00.437+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.362 seconds
[2024-04-21T20:35:30.579+0000] {processor.py:161} INFO - Started process (PID=152) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:35:30.580+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:35:30.582+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:35:30.582+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:35:31.604+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:35:31.655+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:35:31.655+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:35:31.678+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:35:31.678+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:35:31.715+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.139 seconds
[2024-04-21T20:36:01.782+0000] {processor.py:161} INFO - Started process (PID=214) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:36:01.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:36:01.785+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:36:01.784+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:36:02.710+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:36:02.768+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:36:02.767+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:36:02.795+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:36:02.795+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:36:02.838+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.060 seconds
[2024-04-21T20:36:32.987+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:36:32.988+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:36:32.990+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:36:32.990+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:36:34.063+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:36:34.402+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:36:34.398+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:36:34.451+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:36:34.451+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:36:34.623+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.640 seconds
[2024-04-21T20:37:04.778+0000] {processor.py:161} INFO - Started process (PID=332) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:37:04.779+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:37:04.781+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:37:04.781+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:37:05.575+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:37:05.628+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:37:05.627+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:37:05.649+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:37:05.649+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:37:05.682+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 0.907 seconds
[2024-04-21T20:37:35.797+0000] {processor.py:161} INFO - Started process (PID=393) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:37:35.798+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:37:35.801+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:37:35.800+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:37:36.771+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:37:36.824+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:37:36.823+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:37:36.846+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:37:36.845+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:37:36.882+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.088 seconds
[2024-04-21T20:38:06.983+0000] {processor.py:161} INFO - Started process (PID=451) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:38:06.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:38:06.987+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:38:06.987+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:38:08.065+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:38:08.118+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:38:08.117+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:38:08.140+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:38:08.140+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:38:08.174+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.193 seconds
[2024-04-21T20:38:38.773+0000] {processor.py:161} INFO - Started process (PID=508) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:38:38.774+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:38:38.777+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:38:38.776+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:38:40.069+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:38:40.130+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:38:40.129+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:38:40.155+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:38:40.154+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:38:40.190+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.420 seconds
[2024-04-21T20:39:10.441+0000] {processor.py:161} INFO - Started process (PID=565) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:39:10.443+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:39:10.445+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:39:10.445+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:39:11.699+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:39:21.813+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:39:21.745+0000] {dagbag.py:649} ERROR - Failed to write serialized DAG: /opt/airflow/dags/Airflow/dags_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host 'mysql' (-3)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T20:39:21.829+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:39:21.828+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:39:43.052+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:39:42.462+0000] {dagbag.py:649} ERROR - Failed to write serialized DAG: /opt/airflow/dags/Airflow/dags_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host 'mysql' (-3)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T20:39:44.170+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:39:43.469+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:40:08.281+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:40:07.016+0000] {dagbag.py:649} ERROR - Failed to write serialized DAG: /opt/airflow/dags/Airflow/dags_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host 'mysql' (-3)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T20:40:12.601+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:40:11.122+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:40:24.489+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 859, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 895, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 659, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 675, in _sync_to_db
    DAG.bulk_write_to_db(dags.values(), processor_subdir=processor_subdir, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 3059, in bulk_write_to_db
    orm_dags: list[DagModel] = session.scalars(query).unique().all()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1778, in scalars
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host 'mysql' (-3)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T20:40:36.903+0000] {processor.py:161} INFO - Started process (PID=572) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:40:36.905+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:40:36.909+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:40:36.907+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:40:38.383+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:40:38.551+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:40:38.550+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:40:38.590+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:40:38.590+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:40:38.640+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.742 seconds
[2024-04-21T20:40:46.129+0000] {processor.py:161} INFO - Started process (PID=629) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:40:46.131+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:40:46.132+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:40:46.132+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:40:46.472+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:40:46.523+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:40:46.523+0000] {taskinstance.py:2733} ERROR - {'DAG Id': 'workshop2_dags', 'Task Id': 'extract_csv', 'Run Id': 'manual__2024-04-21T20:33:56.093233+00:00', 'Hostname': '6e4579bd97b2', 'External Executor Id': '433d67b7-f828-4382-82bd-4ea5edda54a4'}
[2024-04-21T20:40:46.545+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:40:46.545+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=workshop2_dags, task_id=extract_csv, execution_date=20240421T203356, start_date=20240421T203401, end_date=20240421T204046
[2024-04-21T20:40:46.565+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: workshop2_dags.extract_csv manual__2024-04-21T20:33:56.093233+00:00 [up_for_retry]> in state up_for_retry
[2024-04-21T20:40:46.583+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:40:46.582+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:40:46.758+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:40:46.758+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:40:46.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 0.661 seconds
[2024-04-21T20:40:56.269+0000] {processor.py:161} INFO - Started process (PID=631) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:40:56.270+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:40:56.273+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:40:56.273+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:40:56.624+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:40:56.675+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:40:56.675+0000] {taskinstance.py:2733} ERROR - {'DAG Id': 'workshop2_dags', 'Task Id': 'transformation_db', 'Run Id': 'manual__2024-04-21T20:15:28.756069+00:00', 'Hostname': '6e4579bd97b2', 'External Executor Id': '9d0060a7-b115-4a30-ae73-2dae514f6b9f'}
[2024-04-21T20:40:56.693+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:40:56.693+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=workshop2_dags, task_id=transformation_db, execution_date=20240421T201528, start_date=20240421T203401, end_date=20240421T204056
[2024-04-21T20:40:56.705+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: workshop2_dags.transformation_db manual__2024-04-21T20:15:28.756069+00:00 [failed]> in state failed
[2024-04-21T20:40:56.709+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:40:56.708+0000] {taskinstance.py:2733} ERROR - {'DAG Id': 'workshop2_dags', 'Task Id': 'transformation_db', 'Run Id': 'manual__2024-04-21T20:15:28.756069+00:00', 'Hostname': '6e4579bd97b2', 'External Executor Id': '9d0060a7-b115-4a30-ae73-2dae514f6b9f'}
[2024-04-21T20:40:56.720+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:40:56.719+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=workshop2_dags, task_id=transformation_db, execution_date=20240421T201528, start_date=20240421T203401, end_date=20240421T204056
[2024-04-21T20:40:56.726+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: workshop2_dags.transformation_db manual__2024-04-21T20:15:28.756069+00:00 [failed]> in state failed
[2024-04-21T20:40:56.746+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:40:56.745+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:40:56.910+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:40:56.910+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:40:56.942+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 0.675 seconds
[2024-04-21T20:41:27.290+0000] {processor.py:161} INFO - Started process (PID=688) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:41:27.291+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:41:27.295+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:41:27.294+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:41:27.782+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:41:27.836+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:41:27.836+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:41:27.859+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:41:27.858+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:41:27.892+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 0.606 seconds
[2024-04-21T20:41:58.127+0000] {processor.py:161} INFO - Started process (PID=745) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:41:58.132+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:41:58.140+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:41:58.137+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:42:10.064+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:42:17.856+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:42:16.791+0000] {dagbag.py:649} ERROR - Failed to write serialized DAG: /opt/airflow/dags/Airflow/dags_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on 'mysql:3306' (111)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T20:42:17.859+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:42:17.858+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:42:18.867+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:42:18.867+0000] {process_utils.py:262} INFO - Waiting up to 5 seconds for processes to exit...
[2024-04-21T20:42:34.596+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:42:34.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:42:34.601+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:42:34.600+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:42:35.567+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:42:35.641+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:42:35.641+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:42:35.666+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:42:35.666+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:42:35.698+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.107 seconds
[2024-04-21T20:43:06.588+0000] {processor.py:161} INFO - Started process (PID=96) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:43:06.589+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:43:06.591+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:43:06.591+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:43:07.357+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:43:07.415+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:43:07.414+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:43:07.441+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:43:07.441+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:43:07.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 0.893 seconds
[2024-04-21T20:43:37.598+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:43:37.599+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:43:37.601+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:43:37.601+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:43:38.335+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:43:38.389+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:43:38.389+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:43:38.411+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:43:38.411+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:43:38.444+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 0.849 seconds
[2024-04-21T20:44:08.775+0000] {processor.py:161} INFO - Started process (PID=214) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:44:08.776+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:44:08.779+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:44:08.778+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:44:09.566+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:44:09.617+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:44:09.617+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:44:09.643+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:44:09.643+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:44:09.676+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 0.905 seconds
[2024-04-21T20:44:40.088+0000] {processor.py:161} INFO - Started process (PID=275) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:44:40.090+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:44:40.093+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:44:40.092+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:44:41.519+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:44:41.600+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:44:41.600+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:44:41.623+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:44:41.622+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:44:41.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.576 seconds
[2024-04-21T20:45:11.717+0000] {processor.py:161} INFO - Started process (PID=332) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:45:11.718+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:45:11.720+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:45:11.720+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:45:12.722+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:45:12.782+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:45:12.782+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:45:12.809+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:45:12.809+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:45:12.846+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.132 seconds
[2024-04-21T20:45:43.291+0000] {processor.py:161} INFO - Started process (PID=393) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:45:43.293+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:45:43.296+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:45:43.295+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:45:44.008+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:45:44.078+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:45:44.077+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:45:44.108+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:45:44.108+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:45:44.152+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 0.864 seconds
[2024-04-21T20:46:14.614+0000] {processor.py:161} INFO - Started process (PID=453) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:46:14.616+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:46:14.617+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:46:14.617+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:46:15.654+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:46:15.710+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:46:15.709+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:46:15.734+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:46:15.734+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:46:15.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.164 seconds
[2024-04-21T20:46:45.934+0000] {processor.py:161} INFO - Started process (PID=511) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:46:45.936+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:46:45.938+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:46:45.938+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:46:46.890+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:46:46.941+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:46:46.940+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:46:46.964+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:46:46.964+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:46:47.001+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.062 seconds
[2024-04-21T20:47:17.195+0000] {processor.py:161} INFO - Started process (PID=574) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:47:17.196+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:47:17.199+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:47:17.198+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:47:18.047+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:47:18.098+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:47:18.097+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:47:18.120+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:47:18.120+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:47:18.152+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 0.960 seconds
[2024-04-21T20:47:48.297+0000] {processor.py:161} INFO - Started process (PID=635) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:47:48.298+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T20:47:48.300+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:47:48.300+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:47:49.372+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T20:47:49.423+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:47:49.422+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:47:49.447+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:47:49.447+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T20:47:49.482+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.188 seconds
[2024-04-21T21:00:40.434+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T21:00:40.438+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T21:00:40.458+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:00:40.457+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T21:00:41.255+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T21:00:41.719+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:00:41.719+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T21:00:41.750+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:00:41.750+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T21:00:41.801+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.380 seconds
[2024-04-21T21:01:12.158+0000] {processor.py:161} INFO - Started process (PID=96) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T21:01:12.159+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T21:01:12.162+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:01:12.162+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T21:01:13.541+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T21:01:13.844+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:01:13.843+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T21:01:13.896+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:01:13.896+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T21:01:13.950+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.794 seconds
[2024-04-21T21:03:14.038+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T21:03:14.040+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T21:03:14.045+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:03:14.044+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T21:03:15.558+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T21:03:15.902+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:03:15.896+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T21:03:15.973+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:03:15.973+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T21:03:25.008+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 10.977 seconds
[2024-04-21T21:04:43.333+0000] {processor.py:161} INFO - Started process (PID=97) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T21:04:43.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T21:04:43.337+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:04:43.336+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T21:04:44.565+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T21:04:44.628+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:04:44.627+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T21:04:44.655+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:04:44.655+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T21:04:44.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.466 seconds
[2024-04-21T21:05:14.842+0000] {processor.py:161} INFO - Started process (PID=152) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T21:05:14.844+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T21:05:14.847+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:05:14.846+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T21:05:15.733+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T21:05:15.816+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:05:15.815+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T21:05:15.845+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:05:15.845+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T21:05:15.902+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.064 seconds
[2024-04-21T21:05:46.368+0000] {processor.py:161} INFO - Started process (PID=223) to work on /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T21:05:46.370+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Airflow/dags_etl.py for tasks to queue
[2024-04-21T21:05:46.376+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:05:46.375+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T21:05:47.388+0000] {processor.py:840} INFO - DAG(s) 'workshop2_dags' retrieved from /opt/airflow/dags/Airflow/dags_etl.py
[2024-04-21T21:05:47.460+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:05:47.459+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T21:05:47.496+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:05:47.495+0000] {dag.py:3834} INFO - Setting next_dagrun for workshop2_dags to 2024-04-21 00:00:00+00:00, run_after=2024-04-22 00:00:00+00:00
[2024-04-21T21:05:47.552+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Airflow/dags_etl.py took 1.190 seconds
