[2024-04-21T19:51:52.214+0000] {processor.py:161} INFO - Started process (PID=35) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:51:52.216+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T19:51:52.219+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:51:52.219+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:51:52.257+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:51:52.337+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:51:52.336+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T19:51:52.377+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:51:52.377+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 12:00:00+00:00, run_after=2024-04-21 16:00:00+00:00
[2024-04-21T19:51:52.418+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.209 seconds
[2024-04-21T19:52:23.101+0000] {processor.py:161} INFO - Started process (PID=91) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:52:23.104+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T19:52:23.108+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:52:23.107+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:52:23.124+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:52:23.450+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:52:23.450+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T19:52:23.498+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:52:23.498+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 12:00:00+00:00, run_after=2024-04-21 16:00:00+00:00
[2024-04-21T19:52:23.566+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.471 seconds
[2024-04-21T19:52:54.631+0000] {processor.py:161} INFO - Started process (PID=148) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:52:54.634+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T19:52:54.640+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:52:54.638+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:52:54.654+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:52:54.869+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:52:54.868+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T19:52:54.948+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:52:54.947+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 12:00:00+00:00, run_after=2024-04-21 16:00:00+00:00
[2024-04-21T19:52:55.010+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.381 seconds
[2024-04-21T19:53:25.221+0000] {processor.py:161} INFO - Started process (PID=205) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:53:25.230+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T19:53:25.239+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:53:25.237+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:53:25.277+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:53:25.838+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:53:25.826+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T19:53:25.922+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:53:25.922+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 12:00:00+00:00, run_after=2024-04-21 16:00:00+00:00
[2024-04-21T19:53:26.029+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.826 seconds
[2024-04-21T19:54:32.122+0000] {processor.py:161} INFO - Started process (PID=35) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:54:32.124+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T19:54:32.128+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:54:32.127+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:54:32.137+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:54:32.238+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:54:32.237+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T19:54:32.275+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:54:32.275+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 12:00:00+00:00, run_after=2024-04-21 16:00:00+00:00
[2024-04-21T19:54:32.323+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.204 seconds
[2024-04-21T19:55:03.071+0000] {processor.py:161} INFO - Started process (PID=95) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:55:03.079+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T19:55:03.087+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:55:03.085+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:55:05.292+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:55:16.948+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:55:16.948+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T19:55:16.988+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:55:16.988+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 12:00:00+00:00, run_after=2024-04-21 16:00:00+00:00
[2024-04-21T19:55:17.077+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 13.942 seconds
[2024-04-21T19:55:47.705+0000] {processor.py:161} INFO - Started process (PID=160) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:55:47.710+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T19:55:47.722+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:55:47.718+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:55:47.748+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:55:48.053+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:55:48.051+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T19:55:48.117+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:55:48.117+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 12:00:00+00:00, run_after=2024-04-21 16:00:00+00:00
[2024-04-21T19:55:48.194+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.508 seconds
[2024-04-21T19:57:17.030+0000] {processor.py:161} INFO - Started process (PID=173) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:57:17.033+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T19:57:17.039+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:57:17.035+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:57:17.056+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T19:57:27.209+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:57:27.102+0000] {dagbag.py:649} ERROR - Failed to write serialized DAG: /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'mysql' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host 'mysql' (-3)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T19:57:27.227+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:57:27.226+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T19:57:32.548+0000] {logging_mixin.py:188} INFO - [2024-04-21T19:57:32.544+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 12:00:00+00:00, run_after=2024-04-21 16:00:00+00:00
[2024-04-21T19:57:32.631+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 15.610 seconds
[2024-04-21T20:00:54.918+0000] {processor.py:161} INFO - Started process (PID=228) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:00:54.920+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:00:54.925+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:00:54.922+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:00:54.937+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:00:55.102+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:00:55.101+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:00:55.145+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:00:55.145+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:00:55.200+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.289 seconds
[2024-04-21T20:02:54.604+0000] {processor.py:161} INFO - Started process (PID=248) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:02:54.606+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:02:54.608+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:02:54.607+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:02:54.619+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:02:54.766+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:02:54.764+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:02:54.817+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:02:54.816+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:02:54.914+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.314 seconds
[2024-04-21T20:03:25.749+0000] {processor.py:161} INFO - Started process (PID=306) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:03:25.768+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:03:25.770+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:03:25.770+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:03:25.790+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:03:25.902+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:03:25.902+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:03:25.935+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:03:25.934+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:03:25.986+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.244 seconds
[2024-04-21T20:04:20.235+0000] {processor.py:161} INFO - Started process (PID=338) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:04:20.237+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:04:20.240+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:04:20.239+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:04:20.252+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:04:20.371+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:04:20.370+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:04:20.423+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:04:20.422+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:04:20.462+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.232 seconds
[2024-04-21T20:04:51.334+0000] {processor.py:161} INFO - Started process (PID=396) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:04:51.336+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:04:51.338+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:04:51.337+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:04:51.349+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:04:51.475+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:04:51.475+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:04:51.514+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:04:51.513+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:04:51.566+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.239 seconds
[2024-04-21T20:05:21.767+0000] {processor.py:161} INFO - Started process (PID=453) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:05:21.769+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:05:21.772+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:05:21.771+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:05:21.785+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:05:21.908+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:05:21.907+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:05:21.942+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:05:21.942+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:05:21.996+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.234 seconds
[2024-04-21T20:05:52.553+0000] {processor.py:161} INFO - Started process (PID=507) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:05:52.556+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:05:52.558+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:05:52.557+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:05:52.568+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:05:52.672+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:05:52.672+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:05:52.708+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:05:52.707+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:05:52.762+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.213 seconds
[2024-04-21T20:06:42.374+0000] {processor.py:161} INFO - Started process (PID=543) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:06:42.377+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:06:42.380+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:06:42.379+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:06:42.399+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:06:43.018+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:06:43.017+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:06:43.064+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:06:43.064+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:06:43.118+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.752 seconds
[2024-04-21T20:07:13.839+0000] {processor.py:161} INFO - Started process (PID=599) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:07:13.841+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:07:13.844+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:07:13.843+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:07:13.859+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:07:14.012+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:07:14.011+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:07:14.056+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:07:14.055+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:07:14.110+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.278 seconds
[2024-04-21T20:07:44.364+0000] {processor.py:161} INFO - Started process (PID=657) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:07:44.367+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:07:44.370+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:07:44.369+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:07:44.391+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:07:44.598+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:07:44.597+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:07:44.654+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:07:44.653+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:07:44.751+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.393 seconds
[2024-04-21T20:08:16.666+0000] {processor.py:161} INFO - Started process (PID=714) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:08:16.670+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:08:16.677+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:08:16.672+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:08:16.697+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:08:19.085+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:08:19.082+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:08:19.129+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:08:19.128+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:08:19.203+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 1.160 seconds
[2024-04-21T20:08:49.310+0000] {processor.py:161} INFO - Started process (PID=776) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:08:49.313+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:08:49.317+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:08:49.315+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:08:49.331+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:08:49.538+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:08:49.538+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:08:49.577+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:08:49.577+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:08:49.637+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.334 seconds
[2024-04-21T20:09:53.280+0000] {processor.py:161} INFO - Started process (PID=790) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:09:53.285+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:09:53.289+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:09:53.287+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:09:53.328+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:09:54.422+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:09:54.396+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:09:54.599+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:09:54.597+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:09:54.826+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 1.562 seconds
[2024-04-21T20:10:25.484+0000] {processor.py:161} INFO - Started process (PID=846) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:10:25.485+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:10:25.486+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:10:25.486+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:10:25.494+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:10:25.558+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:10:25.557+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:10:25.599+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:10:25.598+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:10:25.668+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.187 seconds
[2024-04-21T20:10:55.855+0000] {processor.py:161} INFO - Started process (PID=903) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:10:55.857+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:10:55.858+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:10:55.858+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:10:55.866+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:10:55.932+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:10:55.932+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:10:55.954+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:10:55.954+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:10:55.992+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.140 seconds
[2024-04-21T20:14:14.853+0000] {processor.py:161} INFO - Started process (PID=35) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:14:14.855+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:14:14.857+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:14:14.856+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:14:14.879+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:14:14.966+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:14:14.965+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:14:14.996+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:14:14.996+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:14:15.049+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.200 seconds
[2024-04-21T20:14:45.404+0000] {processor.py:161} INFO - Started process (PID=92) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:14:45.405+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:14:45.411+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:14:45.411+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:14:45.423+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:14:45.642+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:14:45.642+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:14:45.667+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:14:45.667+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:14:45.705+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.306 seconds
[2024-04-21T20:15:16.499+0000] {processor.py:161} INFO - Started process (PID=149) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:15:16.501+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:15:16.507+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:15:16.507+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:15:16.520+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:15:16.657+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:15:16.656+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:15:16.719+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:15:16.718+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:15:16.788+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.295 seconds
[2024-04-21T20:15:51.129+0000] {processor.py:161} INFO - Started process (PID=210) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:15:51.245+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:15:51.255+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:15:51.251+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:15:51.278+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:15:51.961+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:15:51.911+0000] {dagbag.py:649} ERROR - Failed to write serialized DAG: /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on 'mysql:3306' (111)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T20:15:51.965+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:15:51.964+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:15:52.160+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:15:52.158+0000] {dagbag.py:649} ERROR - Failed to write serialized DAG: /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on 'mysql:3306' (111)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T20:15:52.171+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:15:52.170+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:15:52.955+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:15:52.953+0000] {dagbag.py:649} ERROR - Failed to write serialized DAG: /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on 'mysql:3306' (111)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T20:15:52.960+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:15:52.960+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:15:52.969+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on 'mysql:3306' (111)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 859, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 895, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 659, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 675, in _sync_to_db
    DAG.bulk_write_to_db(dags.values(), processor_subdir=processor_subdir, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 3059, in bulk_write_to_db
    orm_dags: list[DagModel] = session.scalars(query).unique().all()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1778, in scalars
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T20:16:13.785+0000] {processor.py:161} INFO - Started process (PID=35) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:16:13.788+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:16:13.794+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:16:13.793+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:16:13.904+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:16:14.009+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:16:14.008+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:16:14.044+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:16:14.043+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:16:14.086+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.313 seconds
[2024-04-21T20:16:44.475+0000] {processor.py:161} INFO - Started process (PID=91) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:16:44.477+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:16:44.480+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:16:44.480+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:16:44.486+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:16:44.542+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:16:44.542+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:16:44.569+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:16:44.569+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:16:44.602+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.131 seconds
[2024-04-21T20:17:14.672+0000] {processor.py:161} INFO - Started process (PID=148) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:17:14.674+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:17:14.676+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:17:14.676+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:17:14.683+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:17:14.750+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:17:14.749+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:17:14.777+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:17:14.776+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:17:14.814+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.146 seconds
[2024-04-21T20:17:45.133+0000] {processor.py:161} INFO - Started process (PID=205) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:17:45.135+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:17:45.138+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:17:45.137+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:17:45.144+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:17:45.210+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:17:45.210+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:17:45.235+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:17:45.235+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:17:45.272+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.142 seconds
[2024-04-21T20:18:15.777+0000] {processor.py:161} INFO - Started process (PID=262) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:18:15.779+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:18:15.782+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:18:15.782+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:18:15.791+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:18:15.866+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:18:15.866+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:18:15.902+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:18:15.901+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:18:15.942+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.169 seconds
[2024-04-21T20:18:46.143+0000] {processor.py:161} INFO - Started process (PID=319) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:18:46.145+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:18:46.149+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:18:46.148+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:18:46.157+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:18:46.226+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:18:46.225+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:18:46.255+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:18:46.255+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:18:46.295+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.155 seconds
[2024-04-21T20:32:44.070+0000] {processor.py:161} INFO - Started process (PID=35) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:32:44.072+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:32:44.077+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:32:44.076+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:32:44.104+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:32:44.190+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:32:44.190+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:32:44.237+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:32:44.237+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:32:44.299+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.238 seconds
[2024-04-21T20:33:18.804+0000] {processor.py:161} INFO - Started process (PID=35) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:33:18.809+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:33:18.817+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:33:18.817+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:33:18.874+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:33:19.222+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:33:19.221+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:33:19.257+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:33:19.256+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:33:19.308+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.517 seconds
[2024-04-21T20:33:49.738+0000] {processor.py:161} INFO - Started process (PID=91) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:33:49.740+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:33:49.742+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:33:49.742+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:33:49.749+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:33:49.818+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:33:49.817+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:33:49.844+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:33:49.844+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:33:49.881+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.146 seconds
[2024-04-21T20:34:27.576+0000] {processor.py:161} INFO - Started process (PID=35) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:34:27.577+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:34:27.580+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:34:27.580+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:34:27.590+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:34:27.694+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:34:27.693+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:34:27.732+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:34:27.732+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:34:27.779+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.205 seconds
[2024-04-21T20:34:57.885+0000] {processor.py:161} INFO - Started process (PID=91) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:34:57.887+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:34:57.889+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:34:57.889+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:34:57.896+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:34:57.954+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:34:57.954+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:34:57.979+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:34:57.979+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:34:58.016+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.133 seconds
[2024-04-21T20:35:28.333+0000] {processor.py:161} INFO - Started process (PID=148) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:35:28.336+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:35:28.343+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:35:28.342+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:35:28.362+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:35:28.519+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:35:28.518+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:35:28.575+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:35:28.575+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:35:28.646+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.321 seconds
[2024-04-21T20:35:58.898+0000] {processor.py:161} INFO - Started process (PID=205) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:35:58.901+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:35:58.907+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:35:58.906+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:35:58.919+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:35:59.039+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:35:59.039+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:35:59.074+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:35:59.074+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:35:59.122+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.233 seconds
[2024-04-21T20:36:29.339+0000] {processor.py:161} INFO - Started process (PID=262) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:36:29.341+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:36:29.345+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:36:29.344+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:36:29.352+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:36:29.415+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:36:29.415+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:36:29.441+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:36:29.441+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:36:29.473+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.138 seconds
[2024-04-21T20:37:00.360+0000] {processor.py:161} INFO - Started process (PID=319) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:37:00.362+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:37:00.366+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:37:00.365+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:37:00.375+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:37:00.438+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:37:00.438+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:37:00.463+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:37:00.463+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:37:00.498+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.142 seconds
[2024-04-21T20:37:31.146+0000] {processor.py:161} INFO - Started process (PID=376) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:37:31.148+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:37:31.152+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:37:31.150+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:37:31.162+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:37:31.245+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:37:31.245+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:37:31.271+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:37:31.270+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:37:31.304+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.163 seconds
[2024-04-21T20:38:02.018+0000] {processor.py:161} INFO - Started process (PID=433) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:38:02.019+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:38:02.024+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:38:02.021+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:38:02.037+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:38:02.206+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:38:02.206+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:38:02.239+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:38:02.239+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:38:02.275+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.263 seconds
[2024-04-21T20:38:32.621+0000] {processor.py:161} INFO - Started process (PID=490) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:38:32.623+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:38:32.626+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:38:32.625+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:38:32.634+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:38:32.710+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:38:32.710+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:38:32.742+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:38:32.742+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:38:32.789+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.171 seconds
[2024-04-21T20:39:03.050+0000] {processor.py:161} INFO - Started process (PID=547) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:39:03.052+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:39:03.054+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:39:03.054+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:39:03.062+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:39:03.127+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:39:03.127+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:39:03.156+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:39:03.156+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:39:03.195+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.148 seconds
[2024-04-21T20:40:36.913+0000] {processor.py:161} INFO - Started process (PID=573) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:40:36.914+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:40:36.918+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:40:36.917+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:40:36.935+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:40:38.257+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:40:38.256+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:40:38.302+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:40:38.301+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:40:38.362+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 1.454 seconds
[2024-04-21T20:41:09.165+0000] {processor.py:161} INFO - Started process (PID=633) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:41:09.167+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:41:09.169+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:41:09.169+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:41:09.177+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:41:09.262+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:41:09.261+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:41:09.299+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:41:09.298+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:41:09.372+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.211 seconds
[2024-04-21T20:41:39.716+0000] {processor.py:161} INFO - Started process (PID=696) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:41:39.717+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:41:39.720+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:41:39.720+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:41:39.729+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:41:39.792+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:41:39.792+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:41:39.815+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:41:39.815+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:41:39.848+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.137 seconds
[2024-04-21T20:42:16.293+0000] {processor.py:161} INFO - Started process (PID=747) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:42:16.301+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:42:16.311+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:42:16.310+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:42:16.330+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:42:16.833+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:42:16.791+0000] {dagbag.py:649} ERROR - Failed to write serialized DAG: /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on 'mysql:3306' (111)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T20:42:16.843+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:42:16.837+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:42:17.294+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:42:17.292+0000] {dagbag.py:649} ERROR - Failed to write serialized DAG: /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on 'mysql:3306' (111)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T20:42:17.297+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:42:17.296+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:42:17.692+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:42:17.671+0000] {dagbag.py:649} ERROR - Failed to write serialized DAG: /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on 'mysql:3306' (111)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T20:42:17.700+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:42:17.699+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:42:17.706+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on 'mysql:3306' (111)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 859, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 895, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 659, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 675, in _sync_to_db
    DAG.bulk_write_to_db(dags.values(), processor_subdir=processor_subdir, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 3059, in bulk_write_to_db
    orm_dags: list[DagModel] = session.scalars(query).unique().all()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1778, in scalars
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2024-04-21T20:42:34.609+0000] {processor.py:161} INFO - Started process (PID=35) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:42:34.610+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:42:34.614+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:42:34.613+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:42:34.629+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:42:34.727+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:42:34.726+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:42:34.761+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:42:34.760+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:42:34.794+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.189 seconds
[2024-04-21T20:43:05.051+0000] {processor.py:161} INFO - Started process (PID=91) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:43:05.052+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:43:05.055+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:43:05.055+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:43:05.063+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:43:05.126+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:43:05.125+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:43:05.156+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:43:05.156+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:43:05.194+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.147 seconds
[2024-04-21T20:43:35.454+0000] {processor.py:161} INFO - Started process (PID=148) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:43:35.456+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:43:35.458+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:43:35.458+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:43:35.466+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:43:35.524+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:43:35.523+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:43:35.551+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:43:35.550+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:43:35.582+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.132 seconds
[2024-04-21T20:44:05.944+0000] {processor.py:161} INFO - Started process (PID=205) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:44:05.945+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:44:05.947+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:44:05.947+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:44:05.953+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:44:06.008+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:44:06.007+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:44:06.032+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:44:06.032+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:44:06.070+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.130 seconds
[2024-04-21T20:44:36.650+0000] {processor.py:161} INFO - Started process (PID=262) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:44:36.652+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:44:36.658+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:44:36.657+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:44:36.669+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:44:36.758+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:44:36.757+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:44:36.790+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:44:36.790+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:44:36.829+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.186 seconds
[2024-04-21T20:45:07.253+0000] {processor.py:161} INFO - Started process (PID=319) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:45:07.254+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:45:07.258+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:45:07.257+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:45:07.265+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:45:07.342+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:45:07.342+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:45:07.376+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:45:07.376+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:45:07.427+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.178 seconds
[2024-04-21T20:45:37.502+0000] {processor.py:161} INFO - Started process (PID=376) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:45:37.514+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:45:37.517+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:45:37.516+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:45:37.529+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:45:37.625+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:45:37.624+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:45:37.655+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:45:37.655+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:45:37.691+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.195 seconds
[2024-04-21T20:46:08.453+0000] {processor.py:161} INFO - Started process (PID=433) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:46:08.454+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:46:08.457+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:46:08.456+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:46:08.466+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:46:08.527+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:46:08.527+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:46:08.555+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:46:08.555+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:46:08.592+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.143 seconds
[2024-04-21T20:46:39.121+0000] {processor.py:161} INFO - Started process (PID=490) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:46:39.123+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:46:39.125+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:46:39.125+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:46:39.133+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:46:39.199+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:46:39.199+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:46:39.228+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:46:39.228+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:46:39.263+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.145 seconds
[2024-04-21T20:47:09.621+0000] {processor.py:161} INFO - Started process (PID=547) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:47:09.623+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:47:09.625+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:47:09.625+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:47:09.630+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:47:09.690+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:47:09.690+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:47:09.716+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:47:09.716+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:47:09.750+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.131 seconds
[2024-04-21T20:47:40.703+0000] {processor.py:161} INFO - Started process (PID=604) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:47:40.704+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T20:47:40.706+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:47:40.706+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:47:40.712+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T20:47:40.767+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:47:40.766+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T20:47:40.791+0000] {logging_mixin.py:188} INFO - [2024-04-21T20:47:40.791+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T20:47:40.823+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.123 seconds
[2024-04-21T21:00:40.473+0000] {processor.py:161} INFO - Started process (PID=35) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T21:00:40.474+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T21:00:40.479+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:00:40.479+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T21:00:40.511+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T21:00:40.594+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:00:40.594+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T21:00:40.635+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:00:40.634+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T21:00:40.680+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.213 seconds
[2024-04-21T21:01:11.526+0000] {processor.py:161} INFO - Started process (PID=92) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T21:01:11.528+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T21:01:11.534+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:01:11.532+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T21:01:11.550+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T21:01:11.789+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:01:11.789+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T21:01:11.818+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:01:11.817+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T21:01:11.861+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.344 seconds
[2024-04-21T21:03:14.049+0000] {processor.py:161} INFO - Started process (PID=35) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T21:03:14.051+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T21:03:14.054+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:03:14.054+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T21:03:14.072+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T21:03:14.234+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:03:14.233+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T21:03:14.293+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:03:14.292+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T21:03:14.349+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.306 seconds
[2024-04-21T21:04:44.707+0000] {processor.py:161} INFO - Started process (PID=99) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T21:04:44.715+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T21:04:44.722+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:04:44.721+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T21:04:44.732+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T21:04:44.806+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:04:44.806+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T21:04:44.850+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:04:44.849+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T21:04:44.894+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.192 seconds
[2024-04-21T21:05:15.884+0000] {processor.py:161} INFO - Started process (PID=166) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T21:05:15.888+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T21:05:15.891+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:05:15.890+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T21:05:15.898+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T21:05:15.960+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:05:15.960+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T21:05:15.986+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:05:15.986+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T21:05:16.022+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.143 seconds
[2024-04-21T21:05:46.384+0000] {processor.py:161} INFO - Started process (PID=224) to work on /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T21:05:46.386+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py for tasks to queue
[2024-04-21T21:05:46.390+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:05:46.390+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T21:05:46.408+0000] {processor.py:840} INFO - DAG(s) 'latest_only_with_trigger' retrieved from /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py
[2024-04-21T21:05:46.561+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:05:46.561+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-21T21:05:46.607+0000] {logging_mixin.py:188} INFO - [2024-04-21T21:05:46.606+0000] {dag.py:3834} INFO - Setting next_dagrun for latest_only_with_trigger to 2024-04-21 16:00:00+00:00, run_after=2024-04-21 20:00:00+00:00
[2024-04-21T21:05:46.667+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.9/site-packages/airflow/example_dags/example_latest_only_with_trigger.py took 0.294 seconds
