[2024-04-21T20:15:41.705+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: workshop2_dags.transformation_db manual__2024-04-21T20:15:28.756069+00:00 [queued]>
[2024-04-21T20:15:41.748+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: workshop2_dags.transformation_db manual__2024-04-21T20:15:28.756069+00:00 [queued]>
[2024-04-21T20:15:41.749+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-21T20:15:41.790+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): transformation_db> on 2024-04-21 20:15:28.756069+00:00
[2024-04-21T20:15:41.805+0000] {standard_task_runner.py:60} INFO - Started process 81 to run task
[2024-04-21T20:15:41.810+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'workshop2_dags', 'transformation_db', 'manual__2024-04-21T20:15:28.756069+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/Airflow/dags_etl.py', '--cfg-path', '/tmp/tmpzd03pwst']
[2024-04-21T20:15:41.812+0000] {standard_task_runner.py:88} INFO - Job 38: Subtask transformation_db
[2024-04-21T20:15:51.917+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 38 for task transformation_db ((mysql.connector.errors.DatabaseError) 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)
(Background on this error at: https://sqlalche.me/e/14/4xp6); 81)
[2024-04-21T20:15:51.922+0000] {process_utils.py:131} INFO - Sending 15 to group 81. PIDs of all processes in the group: [81]
[2024-04-21T20:15:51.924+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 81
[2024-04-21T20:15:51.952+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=81, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='20:15:41') (81) terminated with exit code -15
