[2024-04-21T20:34:01.750+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: workshop2_dags.transformation_db manual__2024-04-21T20:15:28.756069+00:00 [queued]>
[2024-04-21T20:34:01.792+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: workshop2_dags.transformation_db manual__2024-04-21T20:15:28.756069+00:00 [queued]>
[2024-04-21T20:34:01.793+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-21T20:34:01.835+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): transformation_db> on 2024-04-21 20:15:28.756069+00:00
[2024-04-21T20:34:01.858+0000] {standard_task_runner.py:60} INFO - Started process 74 to run task
[2024-04-21T20:34:01.866+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'workshop2_dags', 'transformation_db', 'manual__2024-04-21T20:15:28.756069+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/Airflow/dags_etl.py', '--cfg-path', '/tmp/tmpvo9g14tx']
[2024-04-21T20:34:01.870+0000] {standard_task_runner.py:88} INFO - Job 46: Subtask transformation_db
[2024-04-21T20:34:08.361+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 46 for task transformation_db ((mysql.connector.errors.DatabaseError) 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)
(Background on this error at: https://sqlalche.me/e/14/4xp6); 74)
[2024-04-21T20:34:08.368+0000] {process_utils.py:131} INFO - Sending 15 to group 74. PIDs of all processes in the group: [74]
[2024-04-21T20:34:08.370+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 74
[2024-04-21T20:34:08.386+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=74, status='terminated', exitcode=1, started='20:34:01') (74) terminated with exit code 1
