[2024-04-21T21:05:18.833+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: workshop2_dags.extract_csv manual__2024-04-21T21:02:30.540069+00:00 [queued]>
[2024-04-21T21:05:18.851+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: workshop2_dags.extract_csv manual__2024-04-21T21:02:30.540069+00:00 [queued]>
[2024-04-21T21:05:18.852+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-21T21:05:18.877+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): extract_csv> on 2024-04-21 21:02:30.540069+00:00
[2024-04-21T21:05:18.885+0000] {standard_task_runner.py:60} INFO - Started process 86 to run task
[2024-04-21T21:05:18.888+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'workshop2_dags', 'extract_csv', 'manual__2024-04-21T21:02:30.540069+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/Airflow/dags_etl.py', '--cfg-path', '/tmp/tmppixab2gh']
[2024-04-21T21:05:18.891+0000] {standard_task_runner.py:88} INFO - Job 59: Subtask extract_csv
[2024-04-21T21:05:19.139+0000] {task_command.py:423} INFO - Running <TaskInstance: workshop2_dags.extract_csv manual__2024-04-21T21:02:30.540069+00:00 [running]> on host 2a6cdc973ec3
[2024-04-21T21:05:19.427+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='workshop2_dags' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-21T21:02:30.540069+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-21T21:02:30.540069+00:00'
[2024-04-21T21:05:19.430+0000] {transf_spotify.py:6} INFO - Extract Data...
[2024-04-21T21:05:19.438+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Airflow/transf_spotify.py", line 7, in extract_csv
    df_spotify = pd.read_csv("./Data/spotify_dataset.csv")
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: './Data/spotify_dataset.csv'
[2024-04-21T21:05:19.494+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=workshop2_dags, task_id=extract_csv, execution_date=20240421T210230, start_date=20240421T210518, end_date=20240421T210519
[2024-04-21T21:05:19.552+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 59 for task extract_csv ([Errno 2] No such file or directory: './Data/spotify_dataset.csv'; 86)
[2024-04-21T21:05:19.585+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-21T21:05:19.658+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
